version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo npm i -g yarn
      - run: yarn
      - run: yarn test
